name: 'Pull request dependency checkout'
description: 'This action checks if there is a pull request in the repo with the same title.'
author: 'Sebastian Reimers'
branding:
  icon: activity
  color: gray-dark
inputs:
  repo:
    description: 'git repo dependency to checkout'
    required: true
  name:
    required: true
  secret:
    required: true
  working-directory:
    required: false
    default: '.'
runs:
  using: "composite"
  steps: 
    - name: checkout 
      run: |
        branch=$(hub branch --show-current)
        pr_title=$(hub pr show -f %t $PR_NUMBER || echo 'no_pull_request_found')
        cd ${{ inputs.working-directory }} && git clone ${{ inputs.repo }} && cd ${{ inputs.name }}
        pr_dependency=$(hub pr list -f "%I;%t%n" | grep "$pr_title" | awk -F';' '{ print $1 }' || echo)
        stable=$(echo $branch | grep stable || echo)
        [ -n "$stable" ] && git checkout stable || true
        [ -n "$pr_dependency" ] && hub pr checkout $pr_dependency || true
      shell: bash -e {0}
      env:
        PR_NUMBER: ${{ github.event.number }}
        GITHUB_TOKEN: ${{ inputs.secret }}
