name: 'Pull request dependency action'
inputs:
  repo:
    description: 'git repo dependency to checkout'
    required: true
  name:
    required: true
  secret:
    required: true
  working-directory:
    required: false
    default: '.'
runs:
  using: "composite"
  steps: 
    - name: checkout 
      run: |
        pr_title=$(hub pr show -f %t $PR_NUMBER || echo 'no_pull_request_found')
        git clone ${{ inputs.repo }} && cd ${{ inputs.name }}
        pr_dependency=$(hub pr list -f "%I;%t%n" | grep "$pr_title" | awk -F';' '{ print $1 }' || echo)
        if [ -n "$pr_dependency" ]; then hub pr checkout $pr_dependency; fi
      shell: bash -e {0}
      working-directory: ${{ inputs.working-directory }}
      env:
        PR_NUMBER: ${{ github.event.number }}
        GITHUB_TOKEN: ${{ inputs.secret }}
